### ISSUE TITLE
Add falco list/macro resources

### ISSUE THREAD

**Issue by heydonovan** [draios/terraform-provider-sysdig#19]
We can create new falco rules, but can't append to the out-of-the-box ones. :)

**Comment by tembleking** [comment]
Hi @heydonovan, thanks for the feedback.

The out-of-the-box rules can't be either removed nor removed. We can add a `data` to retrieve their information if they need to be referenced in Policies created with the Terraform provider.

**Comment by tembleking** [comment]
Hello @heydonovan, thanks for your patience.

I believe this issue is solved by commits https://github.com/draios/terraform-provider-sysdig/commit/ee4828b6abf1f3c49f5efa3c57b6486fd2287756 and https://github.com/draios/terraform-provider-sysdig/commit/d118dfc0f780f0f231ef91b5c99b6947daf708aa.
Can you try this out?

**Comment by tembleking** [comment]
I am marking this issue as closed, if there's any problem with it don't hesitate to open it again. :slightly_smiling_face:
