### ISSUE TITLE
Add option to copy sysdig policy and add overrides

### ISSUE THREAD

**Issue by heydonovan** [draios/terraform-provider-sysdig#21]
If we create our own rule, and associate it with a sysdig policy, we can't destroy it. We would need to copy the entire policy, and then add them. Of course, once the policies have been updated, we would lose out on those upstream changes.

**Comment by tembleking** [comment]
Hi @heydonovan. First, thanks for your comment.
That's the expected behavior, if a Policy depends on a Rule, that Rule can't be destroyed. 
The correct workflow should be either use the GUI or the IaC to define the resources.

I'll close this issue but feel free to reopen it again and we can discuss about it.
